"""empty message

Revision ID: 025939b8fdf0
Revises: 0cd6ce59252c
Create Date: 2022-08-21 11:50:27.126680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025939b8fdf0'
down_revision = '0cd6ce59252c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
