"""empty message

Revision ID: 0525e17f9997
Revises: 992f52bba130
Create Date: 2022-08-13 11:31:25.872789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0525e17f9997'
down_revision = '992f52bba130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('looking_for_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('seek_descr', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seek_descr', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seek_descr')
    op.drop_column('Venue', 'looking_for_talent')
    op.drop_column('Artist', 'seek_descr')
    op.drop_column('Artist', 'looking_for_venue')
    # ### end Alembic commands ###
