"""empty message

Revision ID: 503a1aae4dfb
Revises: 9a6dc26cfe86
Create Date: 2022-08-13 14:15:33.357627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503a1aae4dfb'
down_revision = '9a6dc26cfe86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('image_link', sa.String(), nullable=False))
    op.add_column('Artist', sa.Column('facebook_link', sa.String(), nullable=False))
    op.add_column('Artist', sa.Column('web_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'web_link')
    op.drop_column('Artist', 'facebook_link')
    op.drop_column('Artist', 'image_link')
    # ### end Alembic commands ###
