"""empty message

Revision ID: 8ea31ea09beb
Revises: b4e9da5519d6
Create Date: 2022-08-15 13:19:10.067134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea31ea09beb'
down_revision = 'b4e9da5519d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artiste_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artiste_venue',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artiste_venue_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='artiste_venue_venue_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id', name='artiste_venue_pkey')
    )
    # ### end Alembic commands ###
