"""empty message

Revision ID: 992f52bba130
Revises: bdd78a12f268
Create Date: 2022-08-13 11:18:40.171181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992f52bba130'
down_revision = 'bdd78a12f268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('web_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genre')
    op.drop_column('Venue', 'web_link')
    # ### end Alembic commands ###
