"""empty message

Revision ID: 9f0138643498
Revises: f91bab1b03d5
Create Date: 2022-08-13 20:45:45.118567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0138643498'
down_revision = 'f91bab1b03d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=False))
    op.drop_column('Artist', 'looking_for_venue')
    op.drop_column('Artist', 'seek_description')
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=False))
    op.drop_column('Venue', 'seek_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seek_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'seeking_description')
    op.add_column('Artist', sa.Column('seek_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('looking_for_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
