"""empty message

Revision ID: e1381aa6c684
Revises: 36e8bb64b703
Create Date: 2022-08-13 12:54:26.378030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1381aa6c684'
down_revision = '36e8bb64b703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id')
    )
    op.add_column('Artist', sa.Column('seek_description', sa.String(), nullable=False))
    op.add_column('Artist', sa.Column('sex', sa.String(length=120), nullable=False))
    op.drop_column('Artist', 'seek_descr')
    op.add_column('Venue', sa.Column('seek_description', sa.String(), nullable=False))
    op.drop_column('Venue', 'seek_descr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seek_descr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'seek_description')
    op.add_column('Artist', sa.Column('seek_descr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'sex')
    op.drop_column('Artist', 'seek_description')
    op.drop_table('tags')
    # ### end Alembic commands ###
